# Basic settings
language: node_js
node_js:
  - "4.4"



# Test script options
before_script:
  # - npm install -g gulp
script: gulp eslint

# Notify CI results
notifications:
  email: false
